# footprint: [[0.1, 0.0], [0.0, 0.1], [-0.1, 0.0], [0.0, -0.1]]
# robot_radius: 0.20
# footprint_padding: 0.01

# robot_base_frame: base_footprint
# update_frequency: 5.0
# publish_frequency: 5.0
# transform_tolerance: 1.5

# resolution: 0.05

# obstacle_range: 2.5
# raytrace_range: 3.0

# #layer definitions
# static:
#     map_topic: /map
#     subscribe_to_updates: true

# # ORIGINAL
# obstacles_laser:
#     observation_sources: laser
#     laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

# #TESTING
# #observation_sources: scan
# #scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}

# inflation:
#     inflation_radius: 0.2

# max_obstacle_height: 0.6
# min_obstacle_height: 0.0

#footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
robot_radius: 0.25
footprint_padding: 0.01

robot_base_frame: base_footprint
update_frequency: 5.0
publish_frequency: 2.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

inflation:
    inflation_radius: 1.0